---
title: "End-to-end reproducible analytics with R"
author: "Kevin Kuo"
date: "June 29, 2015"
output:
  ioslides_presentation:
    smaller: true
---

```{R, include = FALSE}
library(magrittr)
```

## The analytics process

Looks something like:

```{R, echo = FALSE}
library(DiagrammeR)
DiagrammeR("
    graph LR;
      Strategy --> Data;
      Data --> Model;
      Model --> Action;
")
```

## The analytics process

<!---
This slide may not render correctly on the first try.
Refreshing browser seems to fix the issue.
-->

Often, it's closer to:

```{R, echo = FALSE}
DiagrammeR("
    graph LR;
      Strategy --> Data;
      Data --> Strategy;
      Data --> Model;
      Model --> Strategy;
      Model --> Action;
      Action --> Strategy;
      Action --> Model
")
```

## Takeaways

- Reproducible analytics is really important to help us keep things straight.

> - All of the code used to generate this slide deck is available at https://github.com/kykuo/rii2015

> - You can draw flow diagrams with R!

# Case Study 1: Tornado data exploration

## Tornado data exploration

- Storm events data (2010 ~ 2013) from NOAA (National Oceanic and Atmospheric Administration)

```{R}
list.files("download/")
```

## Tornado data exploration {.smaller}

```{R, include = FALSE}
library(readr)
```

```{R, message = FALSE}
"download/stormdata_2010.csv" %>%
  read_csv %>%
  names
```

## Tornado data exploration

```{R, include = FALSE}
source("R/tornado.R")
```

```{R, message = FALSE, warning = FALSE}
stormData %>%
  filter(type == "Tornado") %>%
  head
```

## Tornado data exploration

- Here's a quick plot of daily tornado *counts*:

```{R, echo = FALSE}
dygraph(stormTS) %>%
 dyOptions(stackedGraph = TRUE)
```

## Tornado data exploration

```{R}
stormData %>%
  filter(type == "Tornado",
         date >= ymd("2011-4-25"), date <= ymd("2011-4-28")) %>%
  group_by(state) %>%
  summarize(count = n(),
            deaths = sum(deaths)) %>%
  arrange(desc(count)) %>%
  head
```

## Tornado data exploration

- Here is a map of the tornados during the outbreak:

```{R, echo = FALSE}
library(leaflet)
tornadoMapData %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(lng = ~ long, lat = ~ lat, radius = ~ deaths,
                   fillOpacity = 0.2, color = "red", stroke = FALSE, popup = deathsPopup)
```

# Case study 2: Insurer-Reinsurer relationships

## Insurer-Reinsurer relationships {.smaller}

- We'll work with ~~fake~~ illustrative data:

```{R, include = FALSE}
source("R/network-graph.R")
```

```{R, message = FALSE, warning = FALSE}
sample_n(companies, 5)
sample_n(treaties, 5)
```

## Insurer-reinsurer relationships

```{R, results = "asis"}
forceNetwork(Links = treaties, Nodes = companies, 
             Source = "cedant", Target = "reinsurer",
             Value = "premiumCeded", NodeID = "company", Nodesize = "size",
             Group = "group", opacity = 0.8,
             colourScale = "d3.scale.category10()")
```

# Case study 3: Predictive modeling

## Predictive modeling

- For this case study, we'll use the `Insurance` dataset from the MASS package.

```{R, include = FALSE}
source("R/glm-example.R")
```

```{R, echo = FALSE}
head(Insurance2, 10)
```

- We'll fit poisson regression models to predict claim count and validate results graphically

## Predictive modeling {.smaller}

- Here's a 3-fold relativity table. If the model is *stable* we would expect the estimates to be similar across different samples.

```{R, message = FALSE, warning = FALSE, echo = FALSE}
library(DT)
relativities %>% 
  datatable %>% 
  formatRound(2:(nFolds + 1), digits = 2)
```

## Predictive modeling

```{R, echo = FALSE}
relativityPlots[1]
```

## Predictive modeling

```{R, echo = FALSE}
relativityPlots[2]
```

## Predictive modeling

```{R, echo = FALSE}
relativityPlots[3]
```

## Predictive modeling

- Here is an out-of-sample predicted vs. actual plot, which shows how the model performs in each quantile range of the predicted values:

```{R, echo = FALSE, message = FALSE}
library(rcdimple)
liftChartData %>%
  dimple(x = c("bin", "variable"), y = "value", type = "bar", groups = "variable") %>%
  xAxis(type = "addCategoryAxis", title = "Predicted quantile") %>%
  yAxis(type = "addMeasureAxis", title = "Value") %>%
  add_legend() %>%
  add_title("Out of sample lift chart")
```
